### ISSUE TITLE
关于使用request-promise的问题

### ISSUE THREAD

**Issue by plh97** [lijundong/gitcard#1]
我想知道，你是不是用request-promise来模拟get请求，
```js
let option = {
        uri: 'https://github.com/login/oauth/access_token?client_id=' + clientId + '&client_secret=' + clientSecret + '&code=' + code,
        json: true
    } 
let tokenResp = await rp(option);
```
因为我这样发请求，406，

```
  StatusCodeError: 406 - " "
      at new StatusCodeError (D:\WWW\chat\node_modules\request-promise-core\lib\errors.js:32:15)
      at Request.plumbing.callback (D:\WWW\chat\node_modules\request-promise-core\lib\plumbing.js:104:33)
      at Request.RP$callback [as _callback] (D:\WWW\chat\node_modules\request-promise-core\lib\plumbing.js:46:31)
      at Request.self.callback (D:\WWW\chat\node_modules\request\request.js:186:22)
      at emitTwo (events.js:135:13)
      at Request.emit (events.js:224:7)
      at Request.<anonymous> (D:\WWW\chat\node_modules\request\request.js:1163:10)
      at emitOne (events.js:125:13)
      at Request.emit (events.js:221:7)
      at IncomingMessage.<anonymous> (D:\WWW\chat\node_modules\request\request.js:1085:12)
      at Object.onceWrapper (events.js:322:30)
      at emitNone (events.js:120:20)
      at IncomingMessage.emit (events.js:218:7)
      at endReadableNT (_stream_readable.js:1054:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by leeonfield** [comment]
server 端用 request-promise 发请求，node 环境需要支持 async/await

**Comment by plh97** [comment]
https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/
额，我突然发现你是a链接完成的github 第一步
```jsx
<a href="https://github.com/login/oauth/authorize?client_id=beb866b2260c1881c515&redirect_uri=https://localhost:443/auth">auth</a>
GET https://github.com/login/oauth/authorize
```
然后在/auth路由里面进行github第二步骤
```jsx
POST https://github.com/login/oauth/access_token  
```
刚开始看不懂，现在看懂了一些，感觉还不错
额，请问你的这套是基于RESTful API设计的么？

**Comment by leeonfield** [comment]
对的，第二篇文章中 Github 授权部分提到了
http://www.lijundong.com/application-with-react-and-node-2th/
